#!/usr/bin/env python3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Probe" / "NativeSentenceReader" / "SentenceReaderNative.swift"

REQUIRED_MARKERS = {
    "OPF spine reading order": "collectOPFSpineChapters",
    "EPUB spine xpath": "local-name()='spine'",
    "top contents button": "NSButton(title: \"目录\"",
    "visible TOC root count": "rootTOCCount",
    "native contents menu": "NSMenu(title: \"目录\")",
    "native contents submenu": "item.submenu = submenu",
    "native contents menu builder": "buildContentsMenu",
    "NCX table of contents": "collectTOCEntries",
    "TOC navMap parsing": "localName: \"navMap\"",
    "EPUB3 nav table of contents": "collectHTMLTOCEntries",
    "EPUB3 nav parsing": "local-name()='nav'",
    "EPUB3 TOC list recursion": "appendHTMLTOCEntries",
    "TOC fallback": "fallbackTOCEntries",
    "reader body spans behind header": "webView.topAnchor.constraint(equalTo: root.topAnchor)",
    "reader body spans behind footer": "equalTo: root.bottomAnchor",
    "reading position storage": "SentenceReader.lastReadingPosition.v1",
    "per-book reading position key": "readingPositionKeyPrefix",
    "reading position save": "saveReadingPosition",
    "reading position restore": "__sentenceReaderRestorePage",
    "reading position relative path": "relativeChapterPath",
    "Reader API client": "final class ReaderAPIClient",
    "Reader API health": "func health(requiredCapabilities:",
    "Reader API runtime script candidates": "readerAPIScriptCandidates",
    "Reader API bundled runtime script": "ReaderRuntime/scripts/run_reader_api.sh",
    "Reader API book create": "func createBook",
    "Reader API export": "func exportBook",
    "Reader API Hermes sync": "func syncBookToHermes",
    "Reader API audio note create": "func createAudioNote",
    "Reader API audio note update": "func updateAudioNote",
    "Reader API position save": "func savePosition",
    "Reader API annotation list": "func listAnnotations",
    "Reader API note persist": "persistNote",
    "Reader API red persist": "persistRed",
    "annotation core v2 flag": "__sentenceReaderAnnotationCoreV2",
    "full annotation restore": "__sentenceReaderApplyAnnotations",
    "Reader API red restore": "__sentenceReaderApplyRedHighlights",
    "note preview event": "notePreview",
    "note preview sheet": "showNotePreview",
    "multi-sentence index parser": "sentenceIndexList",
    "multi-sentence payload bridge": "sentenceIndexPayload",
    "batch red selection": "toggleRedSentences",
    "selected sentences range": "selectedSentences",
    "note marker styling": ".sr-sentence.sr-note",
    "notes rail": "makeNotesRail",
    "notes header button": "notesButton",
    "notes table view": "notesTableView",
    "notes search field": "notesSearchField",
    "notes filter control": "notesFilterControl",
    "notes refresh": "refreshNotes",
    "notes edit": "editSelectedNote",
    "notes delete": "deleteSelectedNote",
    "notes jump": "jumpToNote",
    "multi-book entry model": "struct BookEntry",
    "multi-book library storage": "SentenceReader.bookLibrary.v1",
    "multi-book open button": "openBookButton",
    "multi-book switcher button": "bookSwitcherButton",
    "export button": "exportButton",
    "current book export action": "exportCurrentBook",
    "export app support storage": "appSupportExportsDirectory",
    "sync button": "syncButton",
    "current book sync action": "syncCurrentBook",
    "Hermes sync app support storage": "appSupportHermesSyncDirectory",
    "reader settings model": "struct ReaderSettings",
    "reader settings storage": "SentenceReader.readerSettings.v1",
    "reader settings button": "settingsButton",
    "reader settings menu": "showReaderSettings",
    "reader settings persistence": "saveReaderSettings",
    "reader settings web bridge": "applyReaderSettingsToWebView",
    "reader settings js bridge": "__sentenceReaderApplySettings",
    "reader settings font variable": "--sr-font-size",
    "reader settings line height variable": "--sr-line-height",
    "reader settings margin variable": "--sr-page-margin-x",
    "reader settings warm theme": "theme === 'warm'",
    "multi-book import": "importEPUB",
    "multi-book load entry": "loadBookEntry",
    "multi-book switcher menu": "showBookSwitcher",
    "library main button": "libraryButton",
    "library main window": "showLibraryWindow",
    "library main root view": "mainRootView",
    "library home webview": "libraryHomeWebView",
    "library titlebar drag view": "mainTitlebarDragView",
    "library drag view class": "WindowDragView",
    "library drag view moves window": "mouseDownCanMoveWindow",
    "library drag view performs drag": "window?.performDrag(with: event)",
    "library drag view avoids traffic lights": "titlebarDragView.leadingAnchor.constraint(equalTo: root.leadingAnchor, constant: 86)",
    "library window background movable": "window.isMovableByWindowBackground = true",
    "library webview below drag strip": "libraryWebView.topAnchor.constraint(equalTo: titlebarDragView.bottomAnchor)",
    "launch opens main library": "showMainLibrary()",
    "same-window library mode": "showMainLibrary",
    "same-window reading mode": "hideMainLibraryForReading",
    "library web native navigation delegate": "WKNavigationDelegate",
    "library web native ui delegate": "WKUIDelegate",
    "library web import open panel": "runOpenPanelWith",
    "library web import EPUB and PDF": "allowedContentTypes = [.epub, .pdf]",
    "library native continue interception": "openNativeReaderFromLibraryBookID",
    "library native custom scheme": "url.scheme == \"sentence-reader\"",
    "library native custom host": "url.host == \"open-native\"",
    "library mac app surface": "URLQueryItem(name: \"surface\", value: \"mac-app\")",
    "library dashboard bridge": "libraryDashboard()",
    "library native entry resolver": "nativeBookEntry(fromLibraryBook",
    "library native entry upsert": "upsertAndLoadNativeLibraryEntry",
    "bundled demo honest title": "Click 示例书",
    "library table view": "libraryTableView",
    "library book cell": "makeLibraryBookCell",
    "library import action": "importBookFromLibrary",
    "library open selected": "openSelectedLibraryBook",
    "library reveal internal copy": "revealSelectedLibraryBook",
    "library remove list entry": "removeSelectedLibraryBook",
    "library non-destructive remove": "不删除托管原书、阅读位置、标红、笔记或 PostgreSQL 数据",
    "reader more button": "readerMoreButton",
    "reader more menu": "showReaderMoreMenu",
    "reader simplified header": "WindowDragView(),\n                readingTTSButton,\n                contentsButton,",
    "PDF area annotation button": "private let pdfAreaButton = NSButton(title: \"区域批注\"",
    "PDF area annotation hidden outside PDF": "pdfAreaButton.isHidden = true",
    "EPUB app support storage": "appSupportBooksDirectory",
    "EPUB import ownership copy": "copyImportedEPUBToOwnedLibrary",
    "EPUB import ownership verify": "verifyOwnedEPUBCopy",
    "EPUB import owned path guard": "isOwnedImportedBookFile",
    "EPUB import library normalizer": "normalizedImportedBookEntry",
    "EPUB original delete-safe status": "原 EPUB 可删除",
    "EPUB unzip": "unzipEPUBIfNeeded",
    "EPUB file hash": "fileHash(for:",
    "sentence jump bridge": "__sentenceReaderFocusSentence",
    "note speech controller": "final class NoteSpeechController",
    "note speech persistent audio directory": "audioNotesDirectory",
    "note speech audio note id": "latestAudioNoteID",
    "note speech pending audio note": "createPendingAudioNote",
    "note speech FunASR worker": "funasr_worker.py",
    "note speech FunASR warm service": "startFunASRWarmServiceIfAvailable",
    "note speech FunASR server mode": "--server",
    "note speech FunASR server transcribe": "transcribeWithFunASRServer",
    "note speech FunASR server health": "/health",
    "note speech record button": "开始录音",
    "note speech microphone permission": "AVCaptureDevice.requestAccess",
    "note speech fallback": "SFSpeechURLRecognitionRequest",
    "page edge chapter turn": "post({ type: 'edge'",
    "previous chapter opens at end": "__sentenceReaderGoToEnd",
    "controlled page animation": "280ms cubic-bezier(.18,.86,.20,1)",
    "book-like page curl overlay": "sr-page-flip-overlay",
    "next page curl keyframe": "sr-page-curl-next",
    "previous page curl keyframe": "sr-page-curl-previous",
    "horizontal swipe state machine": "handleHorizontalWheel",
    "queued page turn during animation": "schedulePendingPageTurn",
    "responsive page turn cooldown": "pageTurnCooldownMs = 120",
    "physical wheel gesture boundary": "wheelGestureIdleMs = 220",
    "horizontal swipe threshold": "wheelPageTurnThreshold = 96",
    "horizontal swipe dominance": "wheelDominanceRatio = 1.25",
    "responsive horizontal swipe inertia lock duration": "wheelInertiaLockMs = 180",
    "horizontal swipe inertia lock": "wheelInertiaLockUntil = now + wheelInertiaLockMs",
    "page turn cooldown lock": "pageTurnLockUntil = now + pageTurnCooldownMs",
    "Esc closes attached note sheet": "dismissAttachedSheetIfNeeded",
    "vertical wheel suppression": "event.preventDefault();",
    "immersive chrome monitor": "installReaderChromeMonitor",
    "immersive chrome hidden default": "setReaderChromeVisible(false)",
    "immersive chrome transparent titlebar": "titlebarAppearsTransparent = true",
    "immersive chrome full content view": ".fullSizeContentView",
    "immersive chrome mouse reveal": ".mouseMoved",
    "immersive chrome reader spans behind header": "webView.topAnchor.constraint(equalTo: root.topAnchor)",
    "immersive chrome reader spans behind footer": "readerWebViewBottomConstraint!",
    "iPad LAN top button": "iPadLANButton",
    "iPad LAN action": "showIPadLANReader",
    "iPad LAN API mode": "ensureReaderAPILANAvailable",
    "iPad LAN URL": "preferredIPadLANReaderURL",
    "iPad LAN host env": "READER_API_HOST",
    "iPad LAN route": "/lan/reader",
    "viewport-filled page surface": "height: 100vh !important;",
    "tight bottom page padding": "padding: 2px var(--sr-page-margin-x) 4px !important;",
    "real content width pagination": "measuredContentWidth",
    "pagination sliver guard": "paginationEpsilon",
    "safe page offset": "pageOffsetForIndex",
    "paragraphs can cross pages": "break-inside: auto !important;",
    "image height containment": "max-height: calc(100vh - 16px)",
    "image page break protection": "break-inside: avoid !important;",
}


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    missing = [name for name, marker in REQUIRED_MARKERS.items() if marker not in text]
    if missing:
        print(f"native reader FAIL missing={missing}")
        return 1
    print(f"native reader PASS path={SOURCE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
