from __future__ import annotations


def click_voice_workbench_html() -> str:
    return r"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <title>Tingle</title>
  <script>document.documentElement.dataset.surface=new URLSearchParams(location.search).get('surface')||'mobile';</script>
  <style>
    :root{color-scheme:light;font-family:-apple-system,BlinkMacSystemFont,"Microsoft YaHei",sans-serif;color:#1d1d1f;background:#f5f5f7;--line:#dedee2;--muted:#6e6e73;--red:#e03434;--danger:#bd2c2c;--green:#248a3d;--yellow:#a36a00}
    *{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#f5f5f7}button,input,textarea{font:inherit;letter-spacing:0}button{cursor:pointer}button:disabled{cursor:not-allowed;opacity:.48}
    .capture-surface{position:relative;width:100%;height:100%;display:grid;place-items:center;background:#f5f5f7;padding:72px 24px 36px}.capture-brand{position:absolute;top:max(20px,env(safe-area-inset-top));left:24px;margin:0;font-size:19px;font-weight:650}.icon-button{width:44px;height:44px;border:0;border-radius:7px;background:transparent;color:#3a3a3c;display:grid;place-items:center}.icon-button:hover{background:rgba(0,0,0,.055)}.icon-button:focus-visible,.record-toggle:focus-visible,.pause-toggle:focus-visible{outline:3px solid rgba(0,122,255,.42);outline-offset:3px}.icon-button svg{width:20px;height:20px;stroke:currentColor}
    .capture-core{width:min(100%,520px);display:grid;justify-items:center;grid-template-rows:44px 8px 136px 48px 28px;row-gap:18px}.capture-time{font-variant-numeric:tabular-nums;font-feature-settings:"tnum";font-size:34px;font-weight:400;line-height:44px}.input-level{appearance:none;width:184px;height:6px;border:0;border-radius:3px;overflow:hidden;background:#d7d7dc}.input-level::-webkit-progress-bar{background:#d7d7dc}.input-level::-webkit-progress-value{background:#0a84ff;transition:width .08s linear}.input-level::-moz-progress-bar{background:#0a84ff}
    .record-toggle{width:136px;height:136px;border:0;border-radius:50%;background:var(--red);color:white;display:grid;place-items:center;box-shadow:0 1px 2px rgba(0,0,0,.08);transition:transform .12s ease,filter .12s ease}.record-toggle:hover{filter:brightness(1.05)}.record-toggle:active{transform:scale(.97)}.record-toggle svg{width:48px;height:48px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}.record-toggle .stop-glyph{display:none;width:36px;height:36px;border-radius:5px;background:white}.record-toggle.active .mic-glyph{display:none}.record-toggle.active .stop-glyph{display:block}
    .pause-toggle{width:48px;height:48px;border:1px solid #c7c7cc;border-radius:50%;padding:0;background:#fff;color:#3a3a3c;display:grid;place-items:center;opacity:0;pointer-events:none}.pause-toggle.visible{opacity:1;pointer-events:auto}.pause-toggle svg{width:18px;height:18px;fill:currentColor}.capture-status{max-width:100%;height:28px;display:flex;align-items:center;justify-content:center;color:var(--muted);font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.capture-status.saved{color:var(--green)}.capture-status.paused{color:var(--yellow)}.capture-status.error{color:var(--danger)}
    .history-surface{display:none;width:100%;height:100%;background:#fff}.history-surface.open{display:grid;grid-template-rows:60px minmax(0,1fr)}.history-appbar{display:flex;align-items:center;gap:7px;padding:0 14px;border-bottom:1px solid var(--line);background:#fff}.history-title{font-size:18px;font-weight:650}.history-shell{min-height:0;display:grid;grid-template-columns:minmax(290px,380px) minmax(0,1fr)}.list-pane{min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr);border-right:1px solid var(--line);background:#fff}.list-tools{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:12px;border-bottom:1px solid var(--line)}.search{width:100%;height:38px;border:1px solid #c7c7cc;border-radius:7px;padding:0 11px;background:#fff;outline:none}.search:focus{border-color:#0a84ff;box-shadow:0 0 0 2px rgba(10,132,255,.12)}.secondary,.primary,.danger{min-height:36px;border-radius:7px;padding:7px 11px;font-weight:600}.secondary{background:#fff;color:#27272a;border:1px solid #c7c7cc}.primary{background:#1d1d1f;color:#fff;border:1px solid #1d1d1f}.danger{background:#fff;color:var(--danger);border:1px solid #e2aaa7}.archive-toggle.active{color:#0a6b58;border-color:#8cc4ba;background:#eef8f6}
    #list{overflow:auto;min-height:0}.list-empty{padding:48px 20px;text-align:center;color:var(--muted);font-size:13px}.swipe-row{position:relative;overflow:hidden;background:#ececef}.swipe-actions{display:none;position:absolute;inset:0 0 0 auto;align-items:stretch}.swipe-action{width:84px;border:0;border-radius:0;color:#fff;font-size:13px;font-weight:650}.swipe-action.recover{background:#39775f}.swipe-action.archive{background:#687079}.swipe-action.delete{background:var(--danger)}.inspiration{position:relative;z-index:1;width:100%;display:grid;gap:6px;padding:14px 16px;border:0;border-bottom:1px solid #ececef;border-radius:0;background:#fff;color:#1d1d1f;text-align:left;font-weight:400;transition:transform .16s ease}.inspiration:hover{background:#f7f7f8}.inspiration.active{background:#eef5fb;box-shadow:inset 3px 0 0 #0a84ff}.row-top{display:flex;align-items:flex-start;gap:12px}.row-title{min-width:0;flex:1;font-size:15px;font-weight:650;line-height:1.38;overflow-wrap:anywhere}.row-time{color:var(--muted);font-size:11px;white-space:nowrap}.row-preview{color:#515154;font-size:12px;line-height:1.5;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;min-height:36px;overflow-wrap:anywhere}.row-meta{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:11px}.row-state.processing{color:var(--yellow)}.row-state.failed{color:var(--danger)}
    .detail{min-width:0;overflow:auto;background:#fff}.detail-empty{height:100%;display:grid;place-items:center;color:var(--muted);font-size:13px}.detail-wrap{max-width:820px;margin:0 auto;padding:24px clamp(20px,4vw,52px) 56px}.detail-head{display:grid;gap:10px;padding-bottom:20px;border-bottom:1px solid var(--line)}.detail-title-row{display:flex;align-items:center;gap:8px}.detail-back{display:none}.title-input{min-width:0;flex:1;border:0;background:transparent;padding:0;color:#1d1d1f;font-size:24px;font-weight:650;line-height:1.3;outline:none}.detail-meta{display:flex;gap:9px;flex-wrap:wrap;color:var(--muted);font-size:11px}.detail-meta .failed{color:var(--danger)}.detail-meta .processing{color:var(--yellow)}.failure{margin-top:18px;padding:11px 12px;border-left:3px solid var(--danger);background:#fff1f0;color:#7c2520;font-size:12px;line-height:1.5}.section{padding:20px 0;border-bottom:1px solid var(--line)}.section h2{margin:0 0 10px;font-size:13px;font-weight:650}.section-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.section-head h2{margin:0}audio{width:100%;height:34px}.content-editor{width:100%;min-height:220px;resize:vertical;border:0;background:transparent;padding:0;color:#2b2b2f;font-size:15px;line-height:1.75;outline:none;overflow-wrap:anywhere}details{margin-top:14px;color:var(--muted);font-size:12px}summary{cursor:pointer;font-weight:600}.raw{margin-top:10px;padding:12px;background:#f5f5f7;border-radius:6px;color:#505054;line-height:1.65;white-space:pre-wrap;overflow-wrap:anywhere}.detail-actions{display:flex;gap:8px;flex-wrap:wrap;padding-top:20px}.save-state{min-height:18px;color:var(--muted);font-size:11px}.save-state.error{color:var(--danger)}.delete-dialog{width:min(420px,calc(100vw - 32px));border:0;border-radius:8px;padding:0;background:#fff;color:#1d1d1f;box-shadow:0 18px 48px rgba(0,0,0,.24)}.delete-dialog::backdrop{background:rgba(0,0,0,.34)}.delete-dialog-body{padding:22px 22px 14px}.delete-dialog h2{margin:0 0 9px;font-size:18px}.delete-dialog p{margin:0;color:#515154;font-size:13px;line-height:1.55}.delete-dialog .delete-linked{margin-top:8px;color:#6e6e73}.delete-dialog-error{min-height:18px;margin-top:9px;color:var(--danger);font-size:12px}.delete-dialog-actions{display:flex;justify-content:flex-end;gap:8px;padding:12px 16px 16px;border-top:1px solid var(--line)}
    html[data-surface="tingle-history"] .capture-surface{display:none}html[data-surface="tingle-history"] .history-surface{display:grid;grid-template-rows:minmax(0,1fr)}html[data-surface="tingle-history"] .history-appbar{display:none}
    @media(max-width:760px){.capture-surface{padding-top:64px}.capture-core{transform:translateY(-8px)}.history-surface.open{grid-template-rows:58px minmax(0,1fr)}.history-shell{display:block;height:100%}.list-pane{height:100%;border-right:0}.detail{display:none;height:100%;overflow-x:hidden}.detail-open .list-pane{display:none}.detail-open .detail{display:block}.detail-wrap{width:100%;min-width:0;padding:16px 16px 44px;overflow-x:hidden}.detail-title-row{min-width:0;display:grid;grid-template-columns:auto minmax(0,1fr) auto}.detail-back{display:inline-flex}.title-input{width:100%;max-width:100%;font-size:21px}.failure,.content-editor{max-width:100%;overflow-wrap:anywhere}.row-preview{min-height:0}.swipe-actions{display:flex}.swipe-row.revealed .inspiration{transform:translateX(-168px)}html[data-surface="tingle-history"] .history-shell{height:100vh}.content-editor{min-height:260px}}
    @media(prefers-reduced-motion:reduce){.record-toggle,.input-level::-webkit-progress-value{transition:none}}
  </style>
</head>
<body>
  <main class="capture-surface" id="captureSurface">
    <h1 class="capture-brand">Tingle</h1>
    <div class="capture-core">
      <div class="capture-time" id="captureTime">00:00</div>
      <progress class="input-level" id="inputLevel" max="1" value="0" aria-label="麦克风输入电平"></progress>
      <button class="record-toggle" id="recordToggle" aria-label="开始录音" title="开始录音"><svg class="mic-glyph" viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="3" width="6" height="11" rx="3"></rect><path d="M5.5 11.5a6.5 6.5 0 0 0 13 0M12 18v3M8.5 21h7"></path></svg><span class="stop-glyph" aria-hidden="true"></span></button>
      <button class="pause-toggle" id="pauseToggle" aria-label="暂停录音" title="暂停录音"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 5h3v14H7zM14 5h3v14h-3z"></path></svg></button>
      <div class="capture-status" id="captureStatus" aria-live="polite"></div>
    </div>
  </main>
  <main class="history-surface" id="historySurface">
    <header class="history-appbar"><button class="icon-button" id="captureBack" aria-label="返回录音" title="返回录音"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m15 18-6-6 6-6"></path></svg></button><span class="history-title">灵感</span></header>
    <div class="history-shell">
      <section class="list-pane">
        <div class="list-tools"><input class="search" id="search" placeholder="搜索灵感" aria-label="搜索灵感"><button class="secondary archive-toggle" id="archiveToggle">回收站</button></div>
        <div id="list" aria-live="polite"></div>
      </section>
      <section class="detail" id="detail"><div class="detail-empty">选择一条灵感</div></section>
    </div>
  </main>
  <dialog class="delete-dialog" id="deleteDialog" aria-labelledby="deleteDialogTitle">
    <div class="delete-dialog-body">
      <h2 id="deleteDialogTitle">永久删除这条灵感？</h2>
      <p id="deleteDialogMessage">删除后无法恢复。</p>
      <p class="delete-linked" id="deleteLinkedMessage"></p>
      <div class="delete-dialog-error" id="deleteDialogError" aria-live="polite"></div>
    </div>
    <div class="delete-dialog-actions">
      <button class="secondary" id="deleteCancel">取消</button>
      <button class="danger" id="deleteConfirm">永久删除</button>
    </div>
  </dialog>
<script>
let inspirations=[],selectedID='',selected=null,showArchived=false,historyLoaded=false,pendingDeleteItem=null,swipeSuppressClickUntil=0;
let mediaRecorder=null,chunks=[],stream=null,nativeRecording=false,captureState='idle';
let elapsedBeforeRun=0,runStartedAt=0,timer=0,audioContext=null,analyser=null,meterFrame=0;
let selectedBaselineTitle='',selectedBaselineContent='',nativeRecordingState='idle';
const nativeBridgeSchema='tingle.command_bridge.v1';
const $=id=>document.getElementById(id),nativeHistory=document.documentElement.dataset.surface==='tingle-history';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function accessPath(path){const url=new URL(path,location.origin);return url.pathname+url.search}
async function api(path,options){const response=await fetch(accessPath(path),options),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.detail||payload.error||`HTTP ${response.status}`);return payload}
function fmtDate(value){if(!value)return '';const date=new Date(value);if(Number.isNaN(date.getTime()))return '';const now=new Date(),sameYear=date.getFullYear()===now.getFullYear();return new Intl.DateTimeFormat('zh-CN',sameYear?{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}:{year:'numeric',month:'numeric',day:'numeric'}).format(date)}
function fmtDuration(ms){if(ms===null||ms===undefined)return '';const total=Math.max(0,Math.round(Number(ms)/1000));return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function stateText(item){if(item.state==='processing')return '整理中';if(item.state==='failed')return '处理失败';if(item.state==='archived'){if(!item.purge_after)return '历史归档';const deadline=new Date(item.purge_after),remaining=deadline.getTime()-Date.now();if(Number.isNaN(deadline.getTime()))return '已归档';if(remaining<=0)return '等待清理';return `${Math.max(1,Math.ceil(remaining/86400000))} 天后删除`}return ''}
function sourceText(item){return item.source==='mac'?'Mac':item.source==='click_mobile'?'手机':'Hermes'}
function setSaveState(text,error=false){const node=$('saveState');if(!node)return;node.textContent=text||'';node.classList.toggle('error',error)}
function nativePost(type,payload){try{const bridge=window.webkit?.messageHandlers?.tingleCommandBridge;if(bridge)bridge.postMessage({type,payload})}catch(error){console.error('Tingle native bridge failed',error)}}
function editorFocused(){return Boolean(document.activeElement&&['titleInput','contentInput'].includes(document.activeElement.id))}
function hasUnsavedChanges(){if(!selected)return false;const title=$('titleInput'),content=$('contentInput');return Boolean(title&&content&&(title.value!==selectedBaselineTitle||content.value!==selectedBaselineContent))}
function playbackState(){const audio=$('detail')?.querySelector('audio');if(!audio||audio.ended||audio.currentTime===0&&audio.paused)return 'idle';return audio.paused?'paused':'playing'}
function publishNativeState(){nativePost('state',{schema:nativeBridgeSchema,collection:showArchived?'recycle_bin':'inspirations',selectedInspirationID:selectedID||null,selectedTitle:selected?.title||null,selectedContentHash:selected?.content_hash||null,linkedExternalTargetCount:Number(selected?.linked_external_target_count||0),selectedHasAudio:Boolean(selected?.has_audio),editorFocused:editorFocused(),hasUnsavedChanges:hasUnsavedChanges(),playbackState:playbackState(),permanentDeleteAvailable:Boolean(selected?.permanent_delete_available),destructiveConfirmationActive:Boolean($('deleteDialog')?.open)})}
window.__tinglePublishNativeState=publishNativeState;
function setCaptureState(state,text='',error=false){captureState=state;const active=state==='recording'||state==='paused'||state==='finalizing';$('recordToggle').classList.toggle('active',active);$('recordToggle').disabled=state==='preparing'||state==='finalizing'||state==='saved';$('recordToggle').setAttribute('aria-label',active?'停止并保存录音':'开始录音');$('recordToggle').title=active?'停止并保存录音':'开始录音';const canPause=!nativeRecording&&(state==='recording'||state==='paused');$('pauseToggle').classList.toggle('visible',canPause);$('pauseToggle').disabled=!canPause;$('pauseToggle').tabIndex=canPause?0:-1;$('pauseToggle').setAttribute('aria-hidden',canPause?'false':'true');$('captureStatus').textContent=text;$('captureStatus').className=`capture-status ${error?'error':state==='saved'?'saved':state==='paused'?'paused':''}`}
function elapsedMilliseconds(){return elapsedBeforeRun+(captureState==='recording'&&runStartedAt>0?Date.now()-runStartedAt:0)}
function updateTimer(){const total=Math.max(0,Math.floor(elapsedMilliseconds()/1000));$('captureTime').textContent=`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function startTimer(){clearInterval(timer);updateTimer();timer=setInterval(updateTimer,200)}function stopTimer(reset=false){clearInterval(timer);timer=0;if(reset){elapsedBeforeRun=0;runStartedAt=0;$('captureTime').textContent='00:00'}}
function beginClock(){elapsedBeforeRun=0;runStartedAt=Date.now();startTimer()}function pauseClock(){elapsedBeforeRun=elapsedMilliseconds();runStartedAt=0;stopTimer();updateTimer()}function resumeClock(){runStartedAt=Date.now();startTimer()}
function startMeter(input){stopMeter();if(!input||!window.AudioContext&&!window.webkitAudioContext)return;const Context=window.AudioContext||window.webkitAudioContext;audioContext=new Context();analyser=audioContext.createAnalyser();analyser.fftSize=256;audioContext.createMediaStreamSource(input).connect(analyser);const values=new Uint8Array(analyser.fftSize);const tick=()=>{if(!analyser)return;analyser.getByteTimeDomainData(values);let sum=0;for(const value of values){const sample=(value-128)/128;sum+=sample*sample}$('inputLevel').value=Math.min(1,Math.sqrt(sum/values.length)*4);meterFrame=requestAnimationFrame(tick)};tick()}
function stopMeter(){if(meterFrame)cancelAnimationFrame(meterFrame);meterFrame=0;analyser=null;$('inputLevel').value=0;if(audioContext)audioContext.close().catch(()=>{});audioContext=null}
function navigationState(surface,id=''){return{tingleSurface:surface,tingleInspirationID:id||null}}
function openHistory(pushNavigation=true){if(!nativeHistory){$('captureSurface').style.display='none';$('historySurface').classList.add('open');if(pushNavigation&&history.state?.tingleSurface!=='history')history.pushState(navigationState('history'),'')}if(!historyLoaded){historyLoaded=true;loadInspirations(false).catch(()=>{})}publishNativeState()}
function closeHistory(){if(nativeHistory)return;$('historySurface').classList.remove('open');$('captureSurface').style.display='grid';publishNativeState()}
function backToCapture(){if(nativeHistory)return;const surface=history.state?.tingleSurface;if(surface==='detail'){history.go(-2);return}if(surface==='history'){history.back();return}closeHistory()}
function backToHistory(){if(!nativeHistory&&history.state?.tingleSurface==='detail'){history.back();return}clearSelection()}
function applyNavigationState(state){const surface=String(state?.tingleSurface||'capture');if(surface==='detail'&&state?.tingleInspirationID){openHistory(false);selectInspiration(String(state.tingleInspirationID),false).catch(()=>{});return}if(surface==='history'){openHistory(false);clearSelection();return}clearSelection();closeHistory()}
function pageSwipeDirection(dx,dy,elapsed){const horizontal=Math.abs(dx),vertical=Math.abs(dy);if(elapsed>900||horizontal<72||horizontal<vertical*1.35)return 0;return dx<0?-1:1}
function pageSwipeTargetBlocked(target,surface){if(!(target instanceof Element))return true;const control=target.closest('button,input,textarea,audio,dialog,details,summary,a,[contenteditable="true"]');if(!control)return false;return !(surface==='history'&&control.classList.contains('inspiration'))}
function returnFromMobileHistoryGesture(){if(hasUnsavedChanges()){setSaveState('请先保存当前修改',true);return false}closeSwipeRows();if(history.state?.tingleSurface==='detail')backToHistory();else backToCapture();return true}
function bindPageSwipe(node,surface,requiredDirection,action){if(nativeHistory||!node)return;let tracking=false,startX=0,startY=0,startAt=0,hadRevealedRow=false;node.addEventListener('touchstart',event=>{tracking=false;if(event.touches.length!==1||surface==='capture'&&captureState!=='idle'||surface==='history'&&document.body.classList.contains('detail-open')||pageSwipeTargetBlocked(event.target,surface))return;const touch=event.touches[0],pointTarget=document.elementFromPoint(touch.clientX,touch.clientY),edge=Math.max(28,Math.min(40,window.innerWidth*.06));if(pageSwipeTargetBlocked(pointTarget,surface)||touch.clientX<=edge||touch.clientX>=window.innerWidth-edge)return;tracking=true;startX=touch.clientX;startY=touch.clientY;startAt=Date.now();hadRevealedRow=Boolean(document.querySelector('[data-swipe-row].revealed'))},{passive:true});node.addEventListener('touchmove',event=>{if(!tracking||event.touches.length!==1)return;const dx=event.touches[0].clientX-startX,dy=event.touches[0].clientY-startY;if(Math.abs(dy)>Math.abs(dx)&&Math.abs(dy)>12){tracking=false;return}if(Math.sign(dx)===requiredDirection&&Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.35)event.preventDefault()},{passive:false});node.addEventListener('touchend',event=>{if(!tracking)return;tracking=false;const touch=event.changedTouches[0];if(!touch)return;const direction=pageSwipeDirection(touch.clientX-startX,touch.clientY-startY,Date.now()-startAt);if(direction!==requiredDirection)return;if(surface==='capture'&&captureState!=='idle')return;if(surface==='history'&&hadRevealedRow){closeSwipeRows();swipeSuppressClickUntil=Date.now()+350;return}swipeSuppressClickUntil=Date.now()+350;action()},{passive:true});node.addEventListener('touchcancel',()=>{tracking=false},{passive:true})}
window.__tingleSuspendHistory=()=>{const audio=$('detail')?.querySelector('audio');if(audio&&!audio.paused)audio.pause();historyLoaded=false;closeSwipeRows();publishNativeState();return{canRelease:!hasUnsavedChanges()&&!$('deleteDialog')?.open}};
window.__tingleResumeHistory=()=>{openHistory(false);publishNativeState();return true};
function renderList(){const needle=$('search').value.trim().toLowerCase(),shown=inspirations.filter(item=>!needle||`${item.title} ${item.content}`.toLowerCase().includes(needle)),primaryAction=showArchived?'restore':'archive',primaryLabel=showArchived?'恢复':'归档',deleteLabel=showArchived?'立即删除':'删除';$('list').innerHTML=shown.length?shown.map(item=>{const state=stateText(item);return `<div class="swipe-row" data-swipe-row="${esc(item.id)}"><div class="swipe-actions"><button class="swipe-action ${showArchived?'recover':'archive'}" data-swipe-action="${primaryAction}" data-id="${esc(item.id)}">${primaryLabel}</button><button class="swipe-action delete" data-swipe-action="delete" data-id="${esc(item.id)}">${deleteLabel}</button></div><button class="inspiration ${selectedID===item.id?'active':''}" data-id="${esc(item.id)}"><span class="row-top"><span class="row-title">${esc(item.title)}</span><span class="row-time">${esc(fmtDate(item.created_at))}</span></span><span class="row-preview">${esc(item.preview||'')}</span><span class="row-meta"><span>${esc(sourceText(item))}</span>${item.duration_ms?`<span>${esc(fmtDuration(item.duration_ms))}</span>`:''}${state?`<span class="row-state ${esc(item.state)}">${esc(state)}</span>`:''}</span></button></div>`}).join(''):`<div class="list-empty">${showArchived?'回收站是空的':'还没有灵感'}</div>`;document.querySelectorAll('.inspiration[data-id]').forEach(node=>node.onclick=event=>{if(Date.now()<swipeSuppressClickUntil){event.preventDefault();return}selectInspiration(node.dataset.id)});bindSwipeRows()}
function closeSwipeRows(except=null){document.querySelectorAll('[data-swipe-row].revealed').forEach(row=>{if(row!==except)row.classList.remove('revealed')})}
function bindSwipeRows(){document.querySelectorAll('[data-swipe-row]').forEach(row=>{const surface=row.querySelector('.inspiration');let startX=0,startY=0,currentX=0,horizontal=false;surface.addEventListener('touchstart',event=>{if(event.touches.length!==1)return;closeSwipeRows(row);startX=event.touches[0].clientX;startY=event.touches[0].clientY;currentX=startX;horizontal=false},{passive:true});surface.addEventListener('touchmove',event=>{if(event.touches.length!==1)return;currentX=event.touches[0].clientX;const dx=currentX-startX,dy=event.touches[0].clientY-startY;if(!horizontal&&Math.abs(dy)>Math.abs(dx)+8)return;if(!horizontal&&Math.abs(dx)>10)horizontal=true;if(horizontal&&dx<0){event.preventDefault();surface.style.transform=`translateX(${Math.max(-168,dx)}px)`}},{passive:false});surface.addEventListener('touchend',()=>{if(!horizontal){surface.style.transform='';return}const revealed=currentX-startX < -48;surface.style.transform='';row.classList.toggle('revealed',revealed);swipeSuppressClickUntil=Date.now()+350})});document.querySelectorAll('[data-swipe-action]').forEach(button=>button.onclick=event=>{event.preventDefault();event.stopPropagation();performSwipeAction(button.dataset.id,button.dataset.swipeAction).catch(error=>{window.alert(error.message)})})}
async function performSwipeAction(id,action){closeSwipeRows();await selectInspiration(id,action==='delete');if(action==='archive')return archiveSelected();if(action==='restore')return restoreSelected();if(action==='delete'){openPermanentDeleteDialog(selected);return}throw new Error('未知手势操作')}
async function loadInspirations(keepSelection=true){try{const data=await api(`/tingle/inspirations?archived=${showArchived?'true':'false'}&limit=500`);inspirations=data.inspirations||[];if(keepSelection&&selectedID&&!inspirations.some(item=>item.id===selectedID)){selectedID='';selected=null;selectedBaselineTitle='';selectedBaselineContent='';$('detail').innerHTML='<div class="detail-empty">选择一条灵感</div>';document.body.classList.remove('detail-open')}renderList();publishNativeState()}catch(error){$('list').innerHTML=`<div class="list-empty">${esc(error.message)}</div>`;publishNativeState();throw error}}
function latestRaw(item){const versions=(item.transcript_versions||[]).filter(version=>version.version_type==='asr_raw');return versions.length?String(versions[0].content||''):''}
function renderDetail(item){const raw=latestRaw(item),state=stateText(item),isVoice=item.kind==='voice',lifecycleAction=showArchived?'<button class="secondary" id="restore">恢复</button>':'<button class="secondary" id="archive">归档</button>';$('detail').innerHTML=`<div class="detail-wrap"><header class="detail-head"><div class="detail-title-row"><button class="secondary detail-back" id="detailBack">返回</button><input class="title-input" id="titleInput" value="${esc(item.title)}" aria-label="灵感标题"><button class="primary" id="save">保存</button></div><div class="detail-meta"><span>${esc(sourceText(item))}</span><span>${esc(fmtDate(item.created_at))}</span>${item.duration_ms?`<span>${esc(fmtDuration(item.duration_ms))}</span>`:''}${state?`<span class="${esc(item.state)}">${esc(state)}</span>`:''}</div><div class="save-state" id="saveState"></div></header>${item.failure_message?`<div class="failure">${esc(item.failure_message)}<div class="detail-actions"><button class="secondary" id="retry">重试</button></div></div>`:''}${isVoice?`<section class="section"><h2>原音</h2><audio controls preload="metadata" src="${esc(accessPath(item.audio_url))}"></audio></section>`:''}<section class="section"><div class="section-head"><h2>文字</h2></div><textarea class="content-editor" id="contentInput" aria-label="灵感文字">${esc(item.content||'')}</textarea>${raw?`<details><summary>查看原始转写</summary><div class="raw">${esc(raw)}</div></details>`:''}</section><div class="detail-actions">${lifecycleAction}<button class="danger" id="deleteNow">永久删除</button></div></div>`;selectedBaselineTitle=$('titleInput').value;selectedBaselineContent=$('contentInput').value;$('detailBack').onclick=backToHistory;$('save').onclick=()=>saveSelected().catch(()=>{});if($('retry'))$('retry').onclick=()=>retrySelected().catch(()=>{});if($('archive'))$('archive').onclick=()=>archiveSelected().catch(()=>{});if($('restore'))$('restore').onclick=()=>restoreSelected().catch(()=>{});$('deleteNow').onclick=()=>openPermanentDeleteDialog(item);publishNativeState()}
async function selectInspiration(id,pushNavigation=true){try{const data=await api(`/tingle/inspirations/${encodeURIComponent(id)}`);selectedID=id;selected=data.inspiration;renderList();renderDetail(selected);document.body.classList.add('detail-open');if(!nativeHistory&&pushNavigation&&history.state?.tingleSurface!=='detail')history.pushState(navigationState('detail',id),'');publishNativeState()}catch(error){$('list').innerHTML=`<div class="list-empty">${esc(error.message)}</div>`;publishNativeState();throw error}}
async function saveSelected(){if(!selected)throw new Error('请先选择一条灵感');const title=$('titleInput').value.trim(),content=$('contentInput').value.trim();if(!title){const error=new Error('标题不能为空');setSaveState(error.message,true);throw error}if(!content&&selected.content){const error=new Error('已有文字不能清空');setSaveState(error.message,true);throw error}if(!content&&selected.kind!=='voice'){const error=new Error('文字不能为空');setSaveState(error.message,true);throw error}$('save').disabled=true;setSaveState('正在保存');try{const payload={title};if(content)payload.content=content;const data=await api(`/tingle/inspirations/${encodeURIComponent(selected.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});selected=data.inspiration;await loadInspirations();renderDetail(selected);setSaveState('已保存');publishNativeState();return '已保存'}catch(error){setSaveState(error.message,true);publishNativeState();throw error}finally{if($('save'))$('save').disabled=false}}
function clearSelection(){selectedID='';selected=null;selectedBaselineTitle='';selectedBaselineContent='';document.body.classList.remove('detail-open');$('detail').innerHTML='<div class="detail-empty">选择一条灵感</div>';publishNativeState()}
async function archiveSelected(){if(!selected)throw new Error('请先选择一条灵感');try{await api(`/tingle/inspirations/${encodeURIComponent(selected.id)}/archive`,{method:'POST'});clearSelection();await loadInspirations(false);return '已移到回收站'}catch(error){setSaveState(error.message,true);publishNativeState();throw error}}
async function restoreSelected(){if(!selected)throw new Error('请先选择一条灵感');try{await api(`/tingle/inspirations/${encodeURIComponent(selected.id)}/restore`,{method:'POST'});clearSelection();await loadInspirations(false);return '已恢复'}catch(error){setSaveState(error.message,true);publishNativeState();throw error}}
async function retrySelected(){if(!selected)throw new Error('请先选择一条灵感');try{await api(`/tingle/inspirations/${encodeURIComponent(selected.id)}/retry`,{method:'POST'});await selectInspiration(selected.id,false);await loadInspirations();setSaveState('已重新提交');return '已重新提交'}catch(error){setSaveState(error.message,true);publishNativeState();throw error}}
async function switchCollection(archived){showArchived=Boolean(archived);$('archiveToggle').classList.toggle('active',showArchived);$('archiveToggle').textContent=showArchived?'返回灵感':'回收站';clearSelection();await loadInspirations(false);publishNativeState();return showArchived?'已显示回收站':'已显示灵感'}
async function toggleSelectedPlayback(){if(!selected)throw new Error('请先选择一条录音灵感');const audio=$('detail')?.querySelector('audio');if(!audio)throw new Error('这条灵感没有原始音频');if(audio.paused){await audio.play();return '正在播放原音'}audio.pause();return '原音已暂停'}
function closePermanentDeleteDialog(){pendingDeleteItem=null;$('deleteDialogError').textContent='';const dialog=$('deleteDialog');if(dialog.open)dialog.close();publishNativeState()}
function openPermanentDeleteDialog(item){if(!item?.permanent_delete_available||!item?.content_hash){setSaveState('永久删除确认尚未就绪，请重新载入',true);return}pendingDeleteItem=item;$('deleteDialogTitle').textContent='永久删除这条灵感？';$('deleteDialogMessage').textContent=`“${item.title||'未命名灵感'}”将无法恢复。${item.has_audio?' 原始音频也会永久删除。':''}`;const linked=Number(item.linked_external_target_count||0);$('deleteLinkedMessage').textContent=linked?`已沉淀到其他位置的 ${linked} 项内容会保留，不会随此操作删除。`:'其他笔记、任务和知识库内容不会被联动删除。';$('deleteDialogError').textContent='';const dialog=$('deleteDialog');if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');$('deleteConfirm').focus();publishNativeState()}
async function deletePermanentlySelected(confirmation){if(!selected)throw new Error('请先选择一条灵感');if(!selected.permanent_delete_available)throw new Error('安全永久删除服务尚未启用');if(!confirmation?.confirmed)throw new Error('永久删除需要明确确认');const expected=String(confirmation.expectedContentHash||'');if(!expected||expected!==String(selected.content_hash||''))throw new Error('灵感已发生变化，请重新确认');const data=await api(`/tingle/inspirations/${encodeURIComponent(selected.id)}/delete-permanently`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation_intent:'delete_permanently',expected_content_hash:expected,acknowledge_linked_external_targets:Boolean(confirmation.acknowledgesLinkedOutputs)})});if(!data?.receipt)throw new Error('服务没有返回可验证的删除凭据');clearSelection();await loadInspirations(false);return '已永久删除'}
$('deleteCancel').onclick=closePermanentDeleteDialog;$('deleteDialog').addEventListener('cancel',event=>{event.preventDefault();closePermanentDeleteDialog()});$('deleteConfirm').onclick=async()=>{const item=pendingDeleteItem;if(!item)return;const button=$('deleteConfirm');button.disabled=true;$('deleteDialogError').textContent='';try{if(selectedID!==item.id)await selectInspiration(item.id);await deletePermanentlySelected({confirmed:true,expectedContentHash:item.content_hash,acknowledgesLinkedOutputs:true});closePermanentDeleteDialog()}catch(error){$('deleteDialogError').textContent=error.message}finally{button.disabled=false}};
function nativeAck(envelope,ok,message){nativePost('ack',{schema:nativeBridgeSchema,commandID:String(envelope?.commandID||''),ok:Boolean(ok),message:message||null})}
window.__tingleNativeRecordingState=envelope=>{if(envelope?.schema!==nativeBridgeSchema)return false;nativeRecordingState=String(envelope?.recordingState?.state||'idle');return true};
window.__tingleNativeCommand=async envelope=>{if(!envelope||envelope.schema!==nativeBridgeSchema||!envelope.commandID){nativeAck(envelope,false,'系统命令版本不兼容');return false}try{const command=String(envelope.command||'');if(envelope.inspirationID&&selectedID&&envelope.inspirationID!==selectedID&&!['open_inspiration','show_inspirations','show_recycle_bin','reload','focus_search'].includes(command))throw new Error('选中的灵感已改变，请重试');let message='操作完成';switch(command){case 'open_inspiration':if(!envelope.inspirationID)throw new Error('缺少灵感标识');openHistory();if(showArchived)await switchCollection(false);await loadInspirations(false);await selectInspiration(String(envelope.inspirationID),false);message='已打开刚录下的灵感';break;case 'focus_search':openHistory();$('search').focus();message='搜索已就绪';break;case 'save_changes':message=await saveSelected();break;case 'toggle_playback':message=await toggleSelectedPlayback();break;case 'archive':message=await archiveSelected();break;case 'restore':message=await restoreSelected();break;case 'delete_permanently':message=await deletePermanentlySelected(envelope.deleteConfirmation);break;case 'show_inspirations':message=await switchCollection(false);break;case 'show_recycle_bin':message=await switchCollection(true);break;case 'reload':await loadInspirations(true);if(selectedID&&!hasUnsavedChanges())await selectInspiration(selectedID,false);message='已重新载入';break;default:throw new Error('未知系统命令')}publishNativeState();nativeAck(envelope,true,message);return true}catch(error){setSaveState(error.message,true);publishNativeState();nativeAck(envelope,false,error.message);return false}};
function nativeAudioAvailable(){try{return Boolean(window.ClickNativeAudio&&ClickNativeAudio.isAvailable&&ClickNativeAudio.isAvailable()&&ClickNativeAudio.startRecording&&ClickNativeAudio.stopRecording)}catch(error){return false}}
function mobileClient(){return /Android|iPhone|iPad|iPod/i.test(navigator.userAgent||'')||nativeAudioAvailable()}function chooseMime(){for(const type of ['audio/mp4','audio/webm;codecs=opus','audio/webm','audio/ogg'])if(window.MediaRecorder&&MediaRecorder.isTypeSupported(type))return type;return ''}function dataURL(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)})}
async function uploadBlob(blob,duration){setCaptureState('finalizing','正在保存原始音频...');const audio_base64=await dataURL(blob);if(mobileClient()){const payload={audio_base64,mime_type:blob.type||'audio/webm',duration_seconds:duration,source:'mobile_app',source_app:'Click',source_feature:'Tingle',client_capture_id:crypto.randomUUID?crypto.randomUUID():String(Date.now())};await api('/v1/recordings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}else{await api('/voice-records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audio_base64,mime_type:blob.type||'audio/webm',duration_seconds:duration,source:'mac',source_platform:'Tingle Web',metadata:{created_by:'tingle_web'},auto_transcribe:true})})}setCaptureState('saved',`已保存 ${$('captureTime').textContent}`);if(historyLoaded)loadInspirations(false);setTimeout(()=>{stopTimer(true);setCaptureState('idle','')},1200)}
async function startRecording(){if(captureState!=='idle')return;try{setCaptureState('preparing','正在准备麦克风...');if(nativeAudioAvailable()){nativeRecording=true;ClickNativeAudio.startRecording();return}if(!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&window.MediaRecorder))throw new Error('当前设备无法录音');stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=chooseMime();chunks=[];mediaRecorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);mediaRecorder.ondataavailable=event=>{if(event.data&&event.data.size)chunks.push(event.data)};mediaRecorder.onstop=async()=>{const duration=elapsedMilliseconds()/1000;stopTimer();stopMeter();if(stream){stream.getTracks().forEach(track=>track.stop());stream=null}try{await uploadBlob(new Blob(chunks,{type:mime||'audio/webm'}),duration)}catch(error){setCaptureState('idle',`原始音频保存失败：${error.message}`,true)}};mediaRecorder.start();setCaptureState('recording','正在录音');beginClock();startMeter(stream)}catch(error){nativeRecording=false;stopTimer(true);stopMeter();setCaptureState('idle',error.message,true)}}
function stopRecording(){if(captureState!=='recording'&&captureState!=='paused')return;if(captureState==='recording')pauseClock();setCaptureState('finalizing','正在保存原始音频...');if(nativeRecording&&nativeAudioAvailable()){ClickNativeAudio.stopRecording();return}if(mediaRecorder&&(mediaRecorder.state==='recording'||mediaRecorder.state==='paused'))mediaRecorder.stop()}
function togglePause(){if(nativeRecording)return;if(!mediaRecorder)return;if(captureState==='recording'&&mediaRecorder.state==='recording'){mediaRecorder.pause();pauseClock();setCaptureState('paused','已暂停');$('pauseToggle').setAttribute('aria-label','继续录音');$('pauseToggle').title='继续录音'}else if(captureState==='paused'&&mediaRecorder.state==='paused'){mediaRecorder.resume();resumeClock();setCaptureState('recording','正在录音');$('pauseToggle').setAttribute('aria-label','暂停录音');$('pauseToggle').title='暂停录音'}}
$('recordToggle').onclick=()=>captureState==='recording'||captureState==='paused'?stopRecording():startRecording();$('pauseToggle').onclick=togglePause;$('captureBack').onclick=backToCapture;bindPageSwipe($('captureSurface'),'capture',-1,()=>openHistory(true));bindPageSwipe($('historySurface'),'history',1,returnFromMobileHistoryGesture);
window.__clickNativeAudioDidStart=()=>{nativeRecording=true;setCaptureState('recording','正在录音');beginClock()};window.__clickNativeAudioDidStop=()=>{if(captureState==='recording')pauseClock();setCaptureState('finalizing','正在保存原始音频...')};window.__clickNativeAudioDidUpload=async payload=>{nativeRecording=false;if(!payload?.ok){setCaptureState('idle',payload?.error||'原始音频已保存在手机，等待重试',true);return}if(payload?.queued){setCaptureState('saved','原音已保存在手机，等待同步');setTimeout(()=>{stopTimer(true);setCaptureState('idle','')},1600);return}setCaptureState('saved',`已保存 ${$('captureTime').textContent}`);if(historyLoaded)loadInspirations(false);setTimeout(()=>{stopTimer(true);setCaptureState('idle','')},1200)};window.__clickNativeAudioDidError=payload=>{nativeRecording=false;setCaptureState('idle',payload?.error||'原始音频已保存在手机，等待重试',true)};
window.__clickVoiceInboxStartRecording=()=>{if(captureState==='idle'){startRecording();return true}return false};window.__clickVoiceInboxStopRecording=()=>{if(captureState==='recording'||captureState==='paused'){stopRecording();return true}return false};window.__clickVoiceInboxToggleRecording=()=>{captureState==='recording'||captureState==='paused'?stopRecording():startRecording();return true};
$('search').oninput=()=>{renderList();publishNativeState()};$('archiveToggle').onclick=()=>switchCollection(!showArchived).catch(()=>{});
document.addEventListener('focusin',publishNativeState);document.addEventListener('focusout',()=>setTimeout(publishNativeState,0));document.addEventListener('input',event=>{if(['titleInput','contentInput'].includes(event.target?.id))publishNativeState()});for(const eventName of ['play','pause','ended'])document.addEventListener(eventName,publishNativeState,true);
async function refreshVisibleHistory(){if(document.hidden||!historyLoaded||hasUnsavedChanges())return;try{await loadInspirations();if(selectedID)await selectInspiration(selectedID,false)}catch(error){}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshVisibleHistory()});window.addEventListener('pageshow',refreshVisibleHistory);
if(!nativeHistory&&history.state?.tingleSurface!=='capture')history.replaceState(navigationState('capture'),'');window.addEventListener('popstate',event=>applyNavigationState(event.state));setCaptureState('idle','');if(nativeHistory)openHistory(false);publishNativeState();
</script>
</body>
</html>"""
